### ISSUE TITLE
Validator should be able to add additional funds to be destroyed on ejection

### ISSUE THREAD

**Issue by Freydal** [ParadigmFoundation/ParadigmContracts#10]
## Overview
  The design wanted the Validators to put at stake an additional amount over the minimum stake.  The interactions with challenging and risk associated with this needs to be finalized.   

Options associated with this include:
* User adds funds to their stake directly and a challenger must match it.
* User stakes an additional amount that is at stake, but is not available as winnings and will be burned
* This is merely a cushion for a burning rate
 
## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by Freydal** [comment]
* Storage changes
    * Value of additional tokens stored
* Function changes
    * registerListing - add param for additional tokens
    * resolveChallenge - destroy? additional tokens
* Considerations
    * Possible solutions discussed:
        * Tokens are added in a separate pool that is burned on successful challenge
        * Tokens are added to the listing staked balance beyond minimum balance and are distributed on successful challenge
        * ^ + the challenger is required to match the stake to initiate challenge.
        * Take no action, do not add any additional balance and suggest users set a larger burn rate to increase interest in their listing

**Comment by hrharder** [comment]
I think we may need a little bit more discussion around this one, as you seem to highlight above.

Perhaps we try to discuss on a call before proceeding? We can set something up later this week.

**Comment by Freydal** [comment]
Regarding (changes proposed by Liam)[https://github.com/orgs/ParadigmFoundation/teams/protocol/discussions/2] this Issue has been greatly simplified.  Making one change to handle this case.  The only real change required for this is to add a parameter for the staked value.
