### ISSUE TITLE
Validator should  be able to set an earn burn rate that will be executed in batches

### ISSUE THREAD

**Issue by Freydal** [ParadigmFoundation/ParadigmContracts#11]
## Overview
  A major not yet implemented feature is an earn/burn rate associated with the listing entities.  Early adopter listings may have the opportunity to generate tokens by their effort validating transactions.  A listing after the network is established can make itself more desirable by destroying their tokens as payment for the permission to validate transactions.  This concept will have complex interactions with balances reserved for the challenge process.   

Key concerns:
* Earn/burn locations functionality permissions
  * Is DigmToken Burnable by default?  
  * How locked down is the mint functionality. Security here is crucial
* Should earning listing receive minted tokens directly. 
  * Earning listings won't need a pool to burn from.  The tokens could be delivered to the listing owner directly
* How must we protect curation balances from the burning process.
  * Associated with decisions regarding additional stake, Should protect the curating balance or just touch and remove
* Should we piggy back off of certain calls to help automate the earn/burn process.  
  * When burning listings attempt removal or are challenged the burns need to be executed

## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by hrharder** [comment]
Great write up, excited to hear your thoughts and discuss these points more. 

> How locked down is the mint functionality. Security here is crucial

\+ 1

**Comment by hrharder** [comment]
> Should earning listing receive minted tokens directly.

My initial (potentially naive) assumption was a call of the `claimReward()` nature would be made by the listing owner, which would check the correct amount to mint, make that call (presumably as an authorized "minter") to the DIGM contract, and then transfer the balance of the newly minted tokens to the claiming validator listing owner. Immediately I see problems with this due the fact that it doesn't fit the case where the "reward" is negative, and requires a call from the listing owner. 

How are you thinking about approaching this? Do you imagine some kind of system-wide call that executes all mints/burns at once?

**Comment by hrharder** [comment]
Thinking through this also brings up the concept we've discussed of "reward periods". How is the mint/burn rate parameterized for a given listing?

For example, do we think a `reward` of `1000` equates to 1000 wei worth of DIGM being minted for each Ethereum block the listing owner is in the registry? Thus would a `reward` of `-1000` be the burn case for that example.

Doing a reward period on a per-Ethereum block bases avoids the complexity of tracking Rebalance periods on the OrderStream itself, or managing some kind of `reward_period` on the contract side. What do you think @Freydal?

**Comment by Freydal** [comment]
In short.  I think the earn/burn should be a batch operation.  

* The earn/burn process will probably be run together and kicked off by several events because it will need to be up to date before these actions are executed.
* The burn will probably be a single burn call by the registry contract for all the amounts with individual events emitted for the users losses and updates to their treasury system balance.
* The registry contract will need to mint tokens through some call stack(possibly directly).  I don't know if many   mints directly to the address would be more efficient or not. 
* I don't know the best permission setup for the mint.  
  * If it is only one contract that has permission to mint(the treasury perhaps) then any contract that had access to the the single contract would still likely have access to the method. 
  * If only one contract has access and it isn't shared we will never be able to mint for another process in the future.  
  * If we just keep tokens for earning in a balance within the registry that we preconfigure, then instead of burning we just move those tokens to that coffer perhaps we can make the system self contained and limit the token generation.
* I expect the number passed to the contract be in wei.  The ui supplying that perhaps will handle a conversion if necessary.

**Comment by hrharder** [comment]
> The earn/burn process will probably be run together and kicked off by several events because it will need to be up to date before these actions are executed.

Makes sense to me. Going the batch route seems to be sensible, although it calls into question what "user" ends up actually executing that tx that triggers a batch transfer, and if it means sometimes a given call might be more expensive. 

> The burn will probably be a single burn call by the registry contract for all the amounts with individual events emitted for the users losses and updates to their treasury system balance.

Who would end up having to pay gas for this action?

> The registry contract will need to mint tokens through some call stack(possibly directly). I don't know if many mints directly to the address would be more efficient or not.

Makes sense, not sure if I can be helpful in making this decision... Although I suppose the gas efficiency of each is testable in lieu of any security considerations. 

> I expect the number passed to the contract be in wei. The ui supplying that perhaps will handle a conversion if necessary.

As expected. What are you thinking about the time associated with rewards. IE `reward` per each block? `x` blocks? seconds/hours/days/months?

**Comment by Freydal** [comment]
I think doing the calculation in blocks would be best.  As for payment of execution I think cost will be a large factor.  If it is relatively low I think we could just tie it to certain operations and whoever calls them executes it.   I'm not sure of a better solution at the moment if these functions are dependent on it being up to date.

Say if a user wants to challenge a burner but it is way out of sync either that one user needs to be caught up to see if it is just going to be outright removed.  Just doing one listing may be ok if it is written in a way that the batch doesn't get confused.

**Comment by Freydal** [comment]
* Storage changes
    * ValidatorRegistry
        * rewardPeriod - blocks between rewards
        * Listing
            * rewardRate - int
            * confirmation block - start of reward period
            * lastReward block - most recent reward block
        * public key array for earn/burn listings if we decide to batch
* Function changes
    * ValidatorRegistry
        * registerListing add parameter for rewardRate
        * confirmListing - capture confirmationBlock
        * Create function to process rewards.  May need to be called before some processes
            * earn burn from listing owner treasury pool
            * no require permission
            * can result in a touch and remove if treasury has insufficient balance
        * Burns complete required before:
            * Challenge
            * Exit
            * resolve challenge
    * Treasury
        * burnFor
            * only contracts 
            * burn tokens from treasury internal pool
        * mintFor
            * only contracts
            * mint into treasury internal pool
    * Token
        * openly expose burn
        * internal only mint

**Comment by hrharder** [comment]
All looks good. 

One question: what are the units on `rewardRate`? Is that per-block?

Or did we decide the "reward period" would be configurable upon deploy/construction? Unsure if theres a reason for `rewardRate` not to just be tokens per block

**Comment by hrharder** [comment]
I also had a thought, which may be dumb, but worth considering. What if we make some sort of `executeReward(validatorPublicKey)` function public so that any person call it an deliver a payout/burn for any account? I realized that in both the burning and minting case, there is incentive for someone to call it whenever a payout should be executed.

In the case of a burning validator, there is incentive for any token holder to call it as it deflates their own holdings, and theoretically increases its value.

In the case of a minting validator, the incentive obviously exists for them to call the function whenever they should be getting a reward (factoring in gas costs).

I also see no reason this is less secure than having some arbitrary action trigger a batch reward execution. What do you think @Freydal? What am I missing?

**Comment by Freydal** [comment]
This is essentially the direction I was looking to go for now.  Batches may be the direction we take long term, but for now tying an internal call to a executeReward function for a publicKey being acted on.  This function would be public with no call restrictions.  I think it may be useful for it to return a boolean so a call can be executed prior to sending a transaction to see if the call would result in any transfers.

For the units of the rate I have been under the assumption we were going to have a reward period and the units reflected that, but that specification can definitely be changed at your discretion.
