### ISSUE TITLE
Validator Listing removal should have a delay

### ISSUE THREAD

**Issue by Freydal** [ParadigmFoundation/ParadigmContracts#12]
## Overview
Currently removal is immediate.  This placeholder needs to be updated with a process which includes a cooldown period before removal

## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by hrharder** [comment]
Can you elaborate a little on this? I'm looking [here](https://github.com/ParadigmFoundation/ParadigmContracts/blob/master/internal/contracts/validator/ValidatorRegistry.sol#L216) on the `ValidatorRegistry`, and since the actual logic regarding the state of a challenge and the actual call to remove a validator comes from elsewhere (I assume), why is there a need for a delay here?

**Comment by Freydal** [comment]
In the end I would expect there is going to be an ability for an outside user to be able to voluntarily remove a listing.  That is what this function does, but is restricted since it isn't fully implemented.  I expect something like:
1. User executes exitRegisty()
1. Listing is marked for this state and a free to leave block is established.
1. User executes confirmExit() and listing is removed with no penalties.

This is to account for a bad actor not being able to jump ship after acting up giving some time for a challenge, while possibly removing their voting capabilities for the duration.

**Comment by hrharder** [comment]
Ahh of course, makes sense. Is there any precedent for what a sufficient delay is? Or is that a parameter we can wait to establish later on

**Comment by Freydal** [comment]
* Storage changes
    * Add a exitBlock to listing
* Function changes
    * split removeListing to initExit finalizeExit
        * initExit should emit the listing update event to remove voting rights.
        * finalizeExit will be available at exitBlock if not in challenge.

**Comment by hrharder** [comment]
Looks good to me! Will keep an eye on this thread/repo to review once pushed.

**Comment by Freydal** [comment]
Merged ready to review
