### ISSUE TITLE
ValidatorRegistry votes should not be visible until voting is closed

### ISSUE THREAD

**Issue by hrharder** [ParadigmFoundation/ParadigmContracts#3]
## Overview
Right now, votes on registry listings are visible when they are made, which may allow for cheating/coordination attacks. Ideally, individual votes for listings and challenges will not be visible until that challenge/voting period has concluded. 

## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by Freydal** [comment]
* New data to track
    * Poll
        * Replace did vote address making
        * Did commit address mapping
        * Did reveal address mapping
        * Vote address mapping 
        * Commit end
        * Reveal end
    *  Vote
        * Hashed vote
        * Vote
        * Salt
        * Result
* New functions
    * Commit vote - commits a hash encoded vote opinion
    * Reveal vote - reveals the salt and vote to be verified within the contract.

**Comment by StephenFiser** [comment]
@Freydal the commit/reveal process is two transactions from the same user, correct?

**Comment by Freydal** [comment]
Yes.  This would be a two phase process.  We would allow for a voting phase first where users can commit a vote hashed with some salt.  After the commit phase ends the reveal phase will allow the votes to be revealed and tallied.
