### ISSUE TITLE
There should only be one (external) token for the contract system token state should be tracked more closely

### ISSUE THREAD

**Issue by hrharder** [ParadigmFoundation/ParadigmContracts#4]
## Overview
Currently there is one main token which can be split (and re-combined) into two other component tokens, each giving access to a separate right within the system. Ideally, there will be only one token where the following conditions are met:

1. Only one token
1. Balance can be put in treasury, and removed (unless locked for posting or validating)
1. Any/all tokens in treasury count for voting rights on TCR (and general governance)
1. Tokens in Treasury can be locked for posting and/or validating
1. Tokens locked for posting can’t count toward those staked as a validator
1. For validator in the TCR, the Treasury balance can count toward a burning reward, will also be the location for payouts
1. Current rules apply for touch-and-remove if treasury balance goes below slash-able stake for validators
1. ^ or, if a burning validator can’t burn the amount specified in listing for a period, available for touch-and-remove.
1. If tokens are locked for posting, or as a slash-able stake, they still count for voting on the TCR/governance

## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by Freydal** [comment]
Token changes

* Data changed
    * Consolidate the token api with the removal of the 3 token model.
    * Consolidate the token balance for userBalances and change data type to Purse struct
    * Token would be deployed on its own and treasury would be configured in constructor.
* New data to track
    * Struct
        * Purse
            * Users total tokens in system
            * Representation of held balance - Two concepts to consider
                * Contract balances mapping -  Sum should always be less than or equal to users total tokens in system. Tokens never leave the Treasury.
                * Possibly just stored balance - The value of users tokens held in treasury.  Contracts would directly hold the tokens they have claimed on behalf of the user.
* Functions added
    * Deposit (from token holder)
    * Withdraw (from token holder)
    * Claim tokens (from internal contracts)
    * Release tokens (from internal contracts)
* Functions removed
    * Deposit (rename to depositFrom)
    * Withdraw (rename to withdrawFrom)
    * Split
    * Merge
    * currentBalances
    * tokenTransfer
    * mintDigm
* What to consider?
    * Locking tokens during the commit period - or allow committed votes to be destroyed if a user removes tokens.
    * Are adjustBalance and updateBalance needed?

1. Only one token 
    * ✓
1. Balance can be put in treasury, and removed (unless locked for posting or validating)
    * Permissions for this may not be trivial to get right concerning where the balances may be.  (I assumed this point was directed at the token holder)
1. Any/all tokens in treasury count for voting rights on TCR (and general governance) 
    * The concept currently is that tokens enter and exit the token system through the Treasury.  There will be a bit of coupling with the voting contract to facilitate the double counting of tokens for voting.
1. Tokens in Treasury can be locked for posting and/or validating
    * I am considering transferring the tokens directly to the contracts to facilitate the lock as well as disbursements.  The disbursement process of a challenge will be the most complex situation to work though.
1. Tokens locked for posting can’t count toward those staked as a validator
    * The tokens will either be locked in different sub balances within the purse data structure or held by the contracts themselves.
1. For validator in the TCR, the Treasury balance can count toward a burning reward, will also be the location for payouts
    * With both storage mechanisms this process can be handled.  It would be most direct if the contract was able to burn the tokens directly but this would still require a total system tokens owned change in the Treasury.
1. Current rules apply for touch-and-remove if treasury balance goes below slash-able stake for validators
    * Touch and remove should still be possibly with this mechanism.  The tokens stored for a stake may need to 
1. ^ or, if a burning validator can’t burn the amount specified in listing for a period, available for touch-and-remove.
    * I think both concepts allow for internal accounting within the Validator contract itself that would handle this scenario.  This should be possible when the burn functionality is added.
1. If tokens are locked for posting, or as a slash-able stake, they still count for voting on the TCR/governance
    * The tracked total tokens in system is intended to be used for voting.  Currently the idea is to remove committed votes that are no longer valid due to balance changes.

**Comment by Freydal** [comment]
Reopening issue. I was going to track the deeper issue of token balances in a new issue, but decided against it.  I will update the title.
