### ISSUE TITLE
Invert the direction of data, data structures and information stored for the Voting contract.

### ISSUE THREAD

**Issue by Freydal** [ParadigmFoundation/ParadigmContracts#5]
## Overview
Currently the contract is designed to be interacted with from the outside by end users without any prior configuration.  The voting contract would then try grab data out of the ValidatorRegistry specifically to attempt to get state information.  The way this works currently, the only information the users have to specify what they are voting on is the address of the listing holder.  The direction I'm looking to go will allow a challenge transaction to create a poll within the voting contract that will allow users to specify the poll they are voting on and will allow vote grouping within the poll.  The poll would be pre configured with any pertinent information and the ValidatorRegistry would then get poll status based on the saved id.  This would allow the voting contract to provide voting for any contract and will allow finalization logic to be handled in the concerned contract directly(this was an issue with completing the first pass of the process).  

This is a possible prerequisite for #3 by including a data storage mechanism and supporting architecture.
This is possibly related to #4 through the dependence on locking tokens during a polls voting phase.

## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by Freydal** [comment]
* Update the name to be less tied directly to Validator
* Remove ties validator registry
* Pass treasury address in directly
* New data to track
    * Struct
        * Poll
            * Did vote address mapping
            * Vote end time/block
            * Votes for
            * Votes against
            * Poll creator
    * nonce for next poll
    * nonce => Poll
* Functions added
    * Create poll - creates a new poll returning a poll nonce to be broadcasted in event.
    * Poll is final - returns true if the poll is finished and can no longer be modified
    * Poll results - returns the result perhaps boolean or the for and against votes that can be further used elsewhere
* Functions removed
    * Finish - finish actions will be held in external contracts.

**Comment by StephenFiser** [comment]
Overall I like this workflow.

A couple of questions:

- Are you saying that the "challenge" transaction would happen within the registry contract itself? (And is that why you are using the word invert?)

- Once the challenge has started, a poll is created in the Voting contract, right?

- So that means that voting happens in the Voting contract after the challenge is made?

**Comment by Freydal** [comment]
* For the challenge example, yes it would happen in the registry.  My intention though is that any contract could use this voting process.  There would some process in a contract utilizing the voting system that would result in a poll creation fully customized to fit the needs of the contract.
 (The contract currently pulls information out of the validator contract as needed and the validator contract doesn't know about the voting contract.  I intend to invert this relationship to where polls are configured upon create from the outside and the voting contract doesn't know about what contract it is servicing.)
* Yes.  The challenge method would be modified to call a function that creates a poll.  The events emitted would be changed to include relevant information for token holders to reference the poll and commit their vote.
* Yes. Voting will happen exclusively in the voting contract.  The intention is that this contract will provide the voting process for any contract that needs this process.
