### ISSUE TITLE
Voting should allow for users to specify voting power backed by number of tokens they can commit

### ISSUE THREAD

**Issue by Freydal** [ParadigmFoundation/ParadigmContracts#7]
## Overview
Users should provide a number of tokens to commit to a vote to increase the power of their vote.

## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by Freydal** [comment]
* Storage changes
    * Vote
        * Tokens committed (uint)
* Function changes
    * commitVote
        * Add parameter tokensToCommit (uint)
        * Store tokensToCommit to the vote.
    * revealVote
        * Consider the tokens committed when tallying the result.
        * Check balance still available.  Should currently have an existing balance if the committed vote is still available
    * balanceUpdate
        * Only remove the committed votes with a tokensCommitted over the new balance.
* Considerations
    * Perhaps votes do not need to be removed.  They don't really count until revealed and reveal is (should?) check balance anyway

**Comment by hrharder** [comment]
If you have say 100 tokens in the treasury (none locked for registries), does that mean I can vote with a weight of 100 on any number of challenges?

Or if I vote w/ a weight of 60 on one challenge, can I only vote w/ <= 40 tokens on a second challenge?

**Comment by Freydal** [comment]
Any number of challenges for your full systemBalance in the treasury.  This includes tokens locked for registries.  'Commit' in the title may be misleading.

**Comment by Freydal** [comment]
@hrharder I re-opened this to give you a chance to review.  Close when you are satisfied.
