### ISSUE TITLE
Validator challenges should be able to be finalized and payout out appropriately

### ISSUE THREAD

**Issue by Freydal** [ParadigmFoundation/ParadigmContracts#9]
## Overview
 Challenge finalization is not yet implemented.  This should result in listing or challengers contribution should be distributed to the winning side and their voters.
## Action items
- [x] @Freydal do a quick write-up initial implementation ideas
- [x] Discuss/refine potential routes
- [x] Develop spec/tests
- [x] Implement

**Comment by Freydal** [comment]
* Storage changes
    * Voting
        * Poll
            * Add a uint to track total tokens committed to the poll options
            * Change voters to revealedVoters (only if we decide to batch the payout, otherwise i think we can remove)
    * ValidatorRegistry
        * Listing
            * Add an configuration for challenger/listing take of pool
            * Separate out a Challenge struct to store challenges 
                * A history of challenges will allow users to claim rewards for challenges that have ended. 
                * A permanent record of challenge history and results will live in state tying the voting history together
* Function changes
    * Voting
        * Add a function to report the results (maybe just wrap into other functions).
        * Add a function to report tokens committed to winning side by user.
        * Add a function to report the total for winning side.
    * ValidatorRegistry
        * Add a function to claim winnings from a challenge.
            * will call resolveChallenge if it hasn't been resolved
            * will transfer token winnings to user directly
        * Update resolveChallenge to complete and lock its state.
* Considerations
    * Use boolean for vote value. Reduce storage requirement
    * Do we want to prevent users from having to claim challenge rewards individually?
    * Correct naming from tokens earned from voting?  Winnings (vs reward for earn/burn)

**Comment by hrharder** [comment]
All makes sense to me. 

Let me know if I can be helpful with some of the considerations/questions. I imagine much of that will depend on your own testing, specifically about the gas costs associated w/ batch payouts and what actions that can piggy back off of.
